/*
 * LibrosService.java
 * Generated by Xtecuannet-framework Code Generator version 0.2.0
 * Created on 2013-04-27T10:39:52-06
 */


package org.xtecuan.ejemplos.spring.crud.modelo.services;

import org.xtecuan.ejemplos.spring.crud.modelo.entidades.Libros;
import com.xtesoft.xtecuannet.framework.model.services.GenericService;


/**
 *
 * @author xtecuan
 */
public interface LibrosService extends GenericService<Libros> {

}
